dev: ENC[AES256_GCM,data:rV3KtewUdY/65pwZVXVfygA=,iv:Unyx8TLcQpUsht+MTZDBcrBZ9Pqab5iE2eHIX5EbDTs=,tag:AX+zv3jCjXI5kPmZtNTPYg==,type:str]
prod: ENC[AES256_GCM,data:UYmpcpApKQSMuAidpa0/my74kEjwUg==,iv:YqxjvPPgAd85DwO4zG2qjUpSj8T2Az0ZLF8bKnATdQ8=,tag:Cd8LTTtxfkLzqop0FaIHDA==,type:str]
preprod: ENC[AES256_GCM,data:IeHestV2oSDsY7Jn2OMFMiAnmg==,iv:mD+htZkj1g2JCADV5UZ6pfMw/qYAVXv0yROqnR+JnR8=,tag:RTYYY8CHXpAAIEg81zYUzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: http://40.122.204.70:8200
        engine_path: sops
        key_name: spinnaker
        created_at: '2021-02-06T18:18:22Z'
        enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: '2021-02-06T19:54:08Z'
    mac: ENC[AES256_GCM,data:S6S6kUipglVx2Me2rVZ1xQZEc76WVgkoqeOvC73XXFQReRRKFpyj84UcJmjQ+dtRmi/hn8Ip3WSrzW/9OfUIaPNS5VB+O/taUrkcsfxt7AcZf1QCga0H0z8zobwGkgRVuruoIr1ww78r7ljr0Ud6952jzuyB9LDcr0YyH+DFQOg=,iv:LQYohxDi7oRClzTBiydaRzhKZhdl4sL+qM1d7VFtvCY=,tag:w5asWVf3DNHWPHFWPrt71w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
