dev: ENC[AES256_GCM,data:rV3KtewUdY/65pwZVXVfygA=,iv:Unyx8TLcQpUsht+MTZDBcrBZ9Pqab5iE2eHIX5EbDTs=,tag:AX+zv3jCjXI5kPmZtNTPYg==,type:str]
prod: ENC[AES256_GCM,data:KPhd67mfyN6TZ/6KhItedQ==,iv:F1wPP9pbQOPq4vzSLNJaEh3/K7s86sboU0LugPNqjqk=,tag:8hFS6eY8fL/dp3mSsW+zlA==,type:str]
preprod: ENC[AES256_GCM,data:IeHestV2oSDsY7Jn2OMFMiAnmg==,iv:mD+htZkj1g2JCADV5UZ6pfMw/qYAVXv0yROqnR+JnR8=,tag:RTYYY8CHXpAAIEg81zYUzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: http://40.122.204.70:8200
        engine_path: sops
        key_name: spinnaker
        created_at: '2021-02-06T18:18:22Z'
        enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: '2021-02-06T19:49:13Z'
    mac: ENC[AES256_GCM,data:X0gaRiOCnOdlLrHYNGaIqe8jeZFczF/+DCd+PyFBajJWbROyn4raDHZN3LbF0Pe32EPEKVjg9QYUIlvrDD3Ih2XL1cPytUp08N2oV2YC2qAvhVNoBc4ON4Ma/CSpHS2vMGjk4xr8GdkGbHZcCJzQf93ffUje5ejem/QQcSM/b1U=,iv:D+UdOJ+QLCDPNPFZEVnqeBNiVhTWPEZPDvpxyD+CTqs=,tag:FV3eBlGwIdtwS6ygRRQB6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
