dev: ENC[AES256_GCM,data:fj0efvWCNXBxLuOqZExh5tcWr5I=,iv:FHUNTCwFYt6/GKK5MkXtQKXx74AC5X3JubL2WZ/Xj4A=,tag:uViBDk3RUNAPxhgCCLZhvA==,type:str]
prod: ENC[AES256_GCM,data:UYmpcpApKQSMuAidpa0/my74kEjwUg==,iv:YqxjvPPgAd85DwO4zG2qjUpSj8T2Az0ZLF8bKnATdQ8=,tag:Cd8LTTtxfkLzqop0FaIHDA==,type:str]
preprod: ENC[AES256_GCM,data:IeHestV2oSDsY7Jn2OMFMiAnmg==,iv:mD+htZkj1g2JCADV5UZ6pfMw/qYAVXv0yROqnR+JnR8=,tag:RTYYY8CHXpAAIEg81zYUzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: http://40.122.204.70:8200
        engine_path: sops
        key_name: spinnaker
        created_at: '2021-02-06T18:18:22Z'
        enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: '2021-02-06T19:59:18Z'
    mac: ENC[AES256_GCM,data:RdN2sF5O1CN2VtJXI/j6gkHch7zkLdDih0lHRN7StfNFGC+zVNQVZIARlkgxWLoUf9ZPzgq43ETrBr5qlgu0f3r3bARfT2fcM9vD0HccR81RBLwVnFK+93QGDLyNF6k2aAjAN1WV59VfE+/s+u6HaLm4ifhFrJPRv2/Qpdh8+qY=,iv:iwRXDeybeOTj7Dr2oQtAKBukGrrVJdifu+ahLyEQDSs=,tag:BWNFMAmunHST+zG69Q+Byw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
