dev: ENC[AES256_GCM,data:bQDbiWni9Ug1h+0y,iv:ZSw9iINFeaQBlbSgyNhkX0W+41qinIyykkj0Vp9tydo=,tag:cFhVNTKwEnVwZQCDqv7iWg==,type:str]
prod: ENC[AES256_GCM,data:KPhd67mfyN6TZ/6KhItedQ==,iv:F1wPP9pbQOPq4vzSLNJaEh3/K7s86sboU0LugPNqjqk=,tag:8hFS6eY8fL/dp3mSsW+zlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://40.122.204.70:8200
          engine_path: sops
          key_name: spinnaker
          created_at: "2021-02-06T18:18:22Z"
          enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: "2021-02-06T18:18:23Z"
    mac: ENC[AES256_GCM,data:2UTh6NCLTA4QyRsFlqgFLIZaE4pAP8HhRjY/Tuu8vZPKahF0Wj1vOaKBHjo9TbwpcHGFV+CIlMSzufe+vQ8rdw3maWPv95ScxRY77Y1VMM/bnXLar81C8+v9hyIGuel5MFOrVhiBnLBYZRgg7gbZFOl4DDyBPyNKqO3Xx+ratsM=,iv:InhAEWBH14fOcU+h+kXPFvpUGy3heqC53n8iY6be/dQ=,tag:VSJGmQVXCh4iWhy+F1VCCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
