dev: ENC[AES256_GCM,data:bQDbiWni9Ug1h+0y,iv:ZSw9iINFeaQBlbSgyNhkX0W+41qinIyykkj0Vp9tydo=,tag:cFhVNTKwEnVwZQCDqv7iWg==,type:str]
prod: ENC[AES256_GCM,data:KPhd67mfyN6TZ/6KhItedQ==,iv:F1wPP9pbQOPq4vzSLNJaEh3/K7s86sboU0LugPNqjqk=,tag:8hFS6eY8fL/dp3mSsW+zlA==,type:str]
preprod: ENC[AES256_GCM,data:IeHestV2oSDsY7Jn2OMFMiAnmg==,iv:mD+htZkj1g2JCADV5UZ6pfMw/qYAVXv0yROqnR+JnR8=,tag:RTYYY8CHXpAAIEg81zYUzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: http://40.122.204.70:8200
        engine_path: sops
        key_name: spinnaker
        created_at: '2021-02-06T18:18:22Z'
        enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: '2021-02-06T19:42:02Z'
    mac: ENC[AES256_GCM,data:WrIhVh8lVUhEWfwadyQJtvhdXwpgrIs8o1LC2s8nT+PbVkA/l4vWPQJki+cR8i/47kjLbU+PXcV9uvBq/nawKiZnBQtmpD/TsbOwsZTYc+slMPQ0c9OpaMbVZ3DK4TtaBMgGCf30xkvIOYiiYl9ohtxW6KXDm6C8zradiMS4/0Y=,iv:DPNIsupg8eQFAz2tdpNKfZ97jtTK5lqDBTBmMFPFS7w=,tag:CG+nv0x+ksYg3+74HpK1Ng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
