dev: ENC[AES256_GCM,data:IuMGUEpK1AZ+lvIPlTy3HOBq4JTrgA==,iv:sZmZ4gJQtn9YAzo/rsLjPJ7JJzBTvW19z/9cIkCb594=,tag:vyA0aYHjukTcK7YKixRbig==,type:str]
prod: ENC[AES256_GCM,data:UYmpcpApKQSMuAidpa0/my74kEjwUg==,iv:YqxjvPPgAd85DwO4zG2qjUpSj8T2Az0ZLF8bKnATdQ8=,tag:Cd8LTTtxfkLzqop0FaIHDA==,type:str]
preprod: ENC[AES256_GCM,data:IeHestV2oSDsY7Jn2OMFMiAnmg==,iv:mD+htZkj1g2JCADV5UZ6pfMw/qYAVXv0yROqnR+JnR8=,tag:RTYYY8CHXpAAIEg81zYUzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: http://40.122.204.70:8200
        engine_path: sops
        key_name: spinnaker
        created_at: '2021-02-06T18:18:22Z'
        enc: vault:v1:civ9kUlRKTtNUC+RMNFXOCnCrhEFCD6ivkluOEMjFTWGW4xn2VXOKuxDQ9UdX0+2NADLEoEwculmeN6f
    lastmodified: '2021-02-06T20:01:39Z'
    mac: ENC[AES256_GCM,data:jIgAjfRG9GsSd64xiMZd8gIowjdvWDhz6gzMVvxzdHt49Wjta0OpnUDqmeWbC7fiJZjVHEWhiOoX8qqg2lID8f4tXm5TVm6vP/1pQ1Ranpln4+nPjpKYf1sSzrNxNkDaHZlpmlCxMiOaUG1Hs4FER09q9YqIAV0U9G1NqQ+GIxU=,iv:CjMjcGXREa2+OfSO3RVjZicbo/MC/CRD98AnH8MrS44=,tag:B7x9A3UUuNSywrg6iD9T7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
